### ISSUE TITLE
Feature request ipinterface support

### ISSUE THREAD

**Issue by dougsyer** [zenoss/ZenPacks.zenoss.ZenPackLib#108]
I need to be able to subclass ipinterface in zenpacks to change the parent relation.  

I have  several situations that are similar to the implementation in the cisco enterprise zenpack where i need to preserve the ip address glue code and monkeypatches made to ip interface but change the relations to the base ipinterface class.

In most of the higher end zenpacks i have done this the "old way".  I could add an ipinterface relation etc etc but that gets ugly quick with ping and status and layer 2/3 and whatnot..

Maybe an is_interface switch in the yaml?

**Comment by dougsyer** [comment]
i could i suppose subclass ipinterface and wire it in the old way i havent tried that yet.  But inprobabky will today.

**Comment by dougsyer** [comment]
actually i think in the zenpacks i mentioned i was actually doing a 1-M between a subcomponent ie like devices -> chassis -> interfaces.  if you try to ping a ping template to a component I believe the hub service doesnt see any ping templates not bound to the relation os.interfaces.  so Im guessing that allowing ipinterface to not have to be under the os.interfaces relation will be a pain(although maybe you just need to patch the hub service..).  In an ideal world i can add a real linked ip to other components where there isnt really an interface object.

maybe just make it so you can connect an ip interface in via a 1-M relationship as an interim step?  i just was looking at the hub code, didnt look at it yet in great detail.

**Comment by eedgar** [comment]
Doug I am going to mark this as an enhancement for now.  I haven't had time to fully grok what your after here, but its looking like its something outside the original design of zenoss, which is great :)

**Comment by dougsyer** [comment]
Yeah its an enhancement.  Basically i want to be able to implement interfaces that can be pingable/that have ip relations and meyhods that dont have ti be tied to os.ipinterfaces.

**Comment by dougsyer** [comment]
I figured out how to use ipinterface.  The trick other than dealing with the model and gui..which is fairy straight forward is to remember to deal with the device status method and also you need to make sure you deal with the default behavior where a ping down >= warning on manage ip will halt polling..

**Comment by j053ph4** [comment]
IpInterface and other ZenModel class proxies have been added to ZenPackLib 1.1.2 and ZenPackLib 2.0

**Comment by dougsyer** [comment]
Tks
