### ISSUE TITLE
documentation request -> javascript order

### ISSUE THREAD

**Issue by dougsyer** [zenoss/ZenPacks.zenoss.ZenPackLib#115]
love the short_label setting...it has made adjusting the grid for me much much easier...

one thing that would be helpful however is a better understanding of how the orders in the properties vs the orders in the relationship overrides interact.  through trial an error i have the fields in the correct order now but its really just guesswork and id rather understand how the ordering is working.

so for example if I have this:

widget:
  properties:
        myproperty1: {}
            order: 31

  relations:
     widgetdevice:
         order 3.1

in this case, what will come first on the grid? 

mostly i want to make sure that things are working as expected and im not getting lucky by having the order set correctly and find it broken on future updates.

**Comment by j053ph4** [comment]
The "order" parameter has been revised for consistency across different specs and documentation about it has been enhanced for ZenPackLib 2.0.  Order should always be an integer between 1 and 100

**Comment by dougsyer** [comment]
Thanks
