### ISSUE TITLE
feature request:  is it possible to not load the whole yaml every time a daemon starts?

### ISSUE THREAD

**Issue by dougsyer** [zenoss/ZenPacks.zenoss.ZenPackLib#161]
is there a way that you can set it so that the whole yaml file doesnt load during the zenpack import?  I dont think alot of it needs to be read every time we initialize a daemon since alot of it just needs to be imported on zenpack install afaik.

the reason im asking for this is that with a large yaml file it takes a long time to do test runs...also the faster our daemons start the easier it is to keep zenoss up to date as patching is fast(with 4.2) at least.

**Comment by cluther** [comment]
It does look like we could find a way to split YAML loading into three modes.

1. What needs to be loaded at every Python process startup.
    - nothing?
2. What needs to be loaded at every Zope client process startup.
    - classes
    - class_relationships
3. What needs to be loaded only when the ZenPack is being installed.
    - device_classes

**Comment by dougsyer** [comment]
That would help us.  

From a benchmark perspective i dont know if the time we see is just due to the overhead involved with loading the file and or if it has to do with the pyaml parsing or the zenpacklib parsing but i can notice that things load slower and with a bunch of zenpacklib zenpacks I think is helpful to keep this under control.

I think there is a performance gain and also this may seem like its not that big a deal but keeping the load times on the daemons under control helps us because when the collectors load slowly it really effects the amount of time it takes to do collector updates...even when we script them you have to set a timeout at some oint.

**Comment by j053ph4** [comment]
YAML parse/load times have been substantially reduced  and optimized in ZenPackLib 2.0.

**Comment by dougsyer** [comment]
Awesome tks
