### ISSUE TITLE
Duration Threshold issue.

### ISSUE THREAD

**Issue by dougsyer** [zenoss/ZenPacks.zenoss.ZenPackLib#166]
having an issue with duration threshold fields...(see below).

**Comment by dougsyer** [comment]
okay, i think the problem is more to do with trying to assign an int field to a threshold...in my case i am/was trying to assign a default for the percentViolation field which as of duration threshold 1.x is defined as an int.

as a work around, i set the int fields in the zp install method as a work around.

**Comment by dougsyer** [comment]
yeah the duration threshold has a problem where you cant set the violationPercent as a int using zenpacklib.  also it looks like the timePeriod field doesnt like the unicode.  i added a work around by just wrapping a line combining timePeriod with another stirng with a str as a work around.

**Comment by dougsyer** [comment]
Not sure if this is the issue but i noticed in duration threshold the violationPercent field is defined as an int  in _properties but in the interface.py its set as a text field...that may be the issue?

**Comment by dougsyer** [comment]
okay it looks like this is fixed with  zen-24083.  Im pretty sure i had to actually delete the templates to effect the change not sure if there are type comparisons when checking for changes or not...there is a chance this was an older artifact stuck form an eariler zplib version but when i retested after applying 24083 it is working okay.

**Comment by dougsyer** [comment]
there are definately some duration threshold bugs that are triggered using zenpacklib.  probably since one of the fields is defined as an int in the model and a string in the api.  and when some of the fields are set as unicode strings with duration thresold v2.0 there is a silent failure in the threshold...

i think this should probably be closed since I think it is a duration threshold thing more than a zenpacklib thing just want to confirm that.  i have tickets open for the duration threshold stuff in support.

**Comment by j053ph4** [comment]
This was an issue with Python type handling for "extra_parameters" attributes in general.  It has been corrected in ZenPackLib 2.0
