### ISSUE TITLE
Datapoint aliases

### ISSUE THREAD

**Issue by BigChief45** [zenoss/ZenPacks.zenoss.ZenPackLib#171]
I've been trying to assign aliases to a datapoint according to the [documentation](http://zenpacklib.zenoss.com/en/latest/yaml-monitoring-templates.html?highlight=zdevicetemplates#datapoint-fields).

According to the documentation, the aliases property _type_ is defined as:

**Type:**   `map<name, formula>`

However after trying so many different combinations I just cannot set the alias properly, and keep getting this error from the linter:

> zenpack.yaml:134:22: expected a scalar node, but found mapping

Which is strange since the documentation explicitly states _**map**_ as the property type.

Would really appreciate if someone can provide a valid example on how to set an alias (or many aliases) with correct name and formula.

**Comment by dougsyer** [comment]
not sure if this helps but the openstack infrastructure zp uses zenpacklib (and some more traditional methods as well) and is a pretty good reference.

https://github.com/zenoss/ZenPacks.zenoss.OpenStackInfrastructure/blob/develop/ZenPacks/zenoss/OpenStackInfrastructure/zenpack.yaml

**Comment by cluther** [comment]
@BigChief45: I'd also recommend the LinuxMonitor ZenPack. It's the only example I can think of that includes multiple aliases per datapoint in some cases.

https://github.com/zenoss/ZenPacks.zenoss.LinuxMonitor/blob/develop/ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

**Comment by BigChief45** [comment]
A million thanks guys, don't know why I didn't think of that.

In the end, my issue was that I was trying to apply aliases to the datasource instead of the datapoint one level below. Silly.

**Comment by cluther** [comment]
Leaving this issue open with the _docs_ label so we can provide an example of datapoint alias usage.

**Comment by j053ph4** [comment]
Datapoint aliases were revised a bit and documented in ZenPackLib 2.0
