### ISSUE TITLE
Path reporter in docs

### ISSUE THREAD

**Issue by dougsyer** [zenoss/ZenPacks.zenoss.ZenPackLib#173]
Ive done custom path reporters the old way but the nested list parameters specified in the documentation isnt clear to me.  I looked at openstack zp but im not familar enough with the architecture to interpret the yaml into a practical example to use.  In my case  i have component a 1-mc component b, component b 1-mc component c, and i want to be able to see component c totals in the grid of component a.  In the past i have inly done the path reporters across non containing relationships.  

Can you do path reporters on nested 1-Mc rels safely?

**Comment by cluther** [comment]
It's the `extra_paths` class field that is used to control what would have previously been done with an IPathReporter adapter. Aside from the mention in the YAML reference, it is entirely undocumented.

http://zenpacklib.zenoss.com/en/latest/yaml-classes-and-relationships.html#class-fields

For your case where you're only dealing with containing relationships neither an IPathReporter adapter or extra_paths will help. Both of those only apply to non-containing relationships.

Currently to get a count of ComponentC components nested within ComponentA -> ComponentB -> ComponentC you would have do do something like LinuxMonitor does to show the count of snapshot volumes under a volume group where the nesting looks like VolumeGroup -> LogicalVolume -> Snapshot.

First you define a property with api_backendtype set to method:
https://github.com/zenoss/ZenPacks.zenoss.LinuxMonitor/blob/develop/ZenPacks/zenoss/LinuxMonitor/zenpack.yaml#L134

Then you implement the method to do the counting:
https://github.com/zenoss/ZenPacks.zenoss.LinuxMonitor/blob/develop/ZenPacks/zenoss/LinuxMonitor/VolumeGroup.py#L34

**Comment by cluther** [comment]
* Added the _docs_ tag to this issue to get extra_paths documented.
* Added the _enhancement_ tag to this issue to include nested MC counts by default.

**Comment by dougsyer** [comment]
yep i have a counting mixin in my zenpack that i use do do a bunch of rollup counts based on different logic for different components.  i'll do it that way.  also i know how to append more dropdowns in the parent component, i'll just add that through js as a panel...makes sense about the paths dont want to create some kind of infinite loop.

**Comment by j053ph4** [comment]
This documentation was updated with several examples in ZPL 2.0
