### ISSUE TITLE
feature-request, classmethod returning om/rm

### ISSUE THREAD

**Issue by dougsyer** [zenoss/ZenPacks.zenoss.ZenPackLib#24]
I dont know about you all but i always struggle trying to get the om/rm syntax correct in my modelers.

You may have thought of this already but it may make sense to include a class method on the base objects, something like this, to make it easier to create your relmaps:

@classmethod
    def getRM(self, oms):
        return RelationshipMap(modname = self.**module**,
                               relname = 'add your relname here',
                               objmaps = oms)

**Comment by dougsyer** [comment]
i can see a method that tries to get the containing relationship name but since its not a class method i cant get to it on model to auto set my relationship name.

i have a zenpack with alot of classes and using the object to create relationship maps that can be passed to the modeler helps alot with human errors in the modeler.

**Comment by dougsyer** [comment]
this works.

   @classmethod
    def getContRM(cls, oms):
        return RelationshipMap(modname = cls.__module__,
                                   relname = cls.getParentContRelname(),
                                   objmaps = oms)

    @classmethod
    def getParentContRelname(cls):
        """Return name of the parents containing relationship to this class"""
        for relname, relschema in cls._relations:
            if issubclass(relschema.remoteType, ToManyCont):
                return relschema.remoteName

**Comment by dougsyer** [comment]
as a follow up, I may be seing an issue with the above code working with a more complex model im investigating if the issue is this helper classmethod or something else.

**Comment by j053ph4** [comment]
I created ZPS-792 in JIRA to track this enhancement

**Comment by dougsyer** [comment]
Tks.  Im using this as a mixin now.  I just import the class into the modeler and it generates my rm for me saves alot of time
