### ISSUE TITLE
please add a check for valid RRDType

### ISSUE THREAD

**Issue by dougsyer** [zenoss/ZenPacks.zenoss.ZenPackLib#243]
ive gotten burned a few times mis-typing GAUGE/DERIVE etc...yeah i know spellcheck....but im sure im not alone in constantly having to change counters back and forth between GAUGE and DERIVE during development/testing.

what ive found if you do that is that at least in my zepython plugin i get a nasty semi-silent error when trying to write rrds..

ie if you put this in the rrdtype:  SNAKE  or GUAGE or something like that it accepts the value but then causes a wierd issue when trying to write it...i havent tested this with a daemon other than zenpython....

doug

**Comment by j053ph4** [comment]
RRDType validation has been added to ZenPackLib 2.0 along with several other input validation features.

**Comment by dougsyer** [comment]
Thanks
