### ISSUE TITLE
Int editable field gets set ti str.

### ISSUE THREAD

**Issue by dougsyer** [zenoss/ZenPacks.zenoss.ZenPackLib#296]
When i set a property as int and make it editable it gets the correct xtype and you can only select ints in the field...thats good...

But if i check the type of the propert after it gets set to a string.  

I set it to int because the xtype forces the end user to select an integer value i dobt realky care if its an int or  string thats stored but now i have both.  Int for the default values and string for the edited ones.  Im pretty sure this issue predates zenpacklib and i think ive run into this before.  

I mostly use these fields to allow my users to customize their own thresholds so its hard.to notice since i believe the min max fields dont care if you pass a string... but o did notice it when accessing the value in a transform..

**Comment by j053ph4** [comment]
This is resolved in ZPL 2.0

**Comment by dougsyer** [comment]
Tks!
