### ISSUE TITLE
how to order graph points

### ISSUE THREAD

**Issue by dougsyer** [zenoss/ZenPacks.zenoss.ZenPackLib#421]
ive been looking for a way to order graphs and graph points.  Can I assume that the expectation is that graphs and graph points should be listed in the yaml in the order you want them to appear in the crated graphs?

ie.

graphs:
   mygraph1:
       gp1: 
          dpName:  ds_dp1
           stacked: true
      gp1:
           dpName: ds_dp2
           stacked: true
  mygraph2:
       gp3:
            dpName: ds_dp3

my question is, in this case what is the expected order in the gui.

is it
mygraph1:
                          -------
                             dp1
                          -------
                             dp2
                          -------

or the reverse?

**Comment by j053ph4** [comment]
Hi Doug,

You are correct that the expectation is that the YAML order should be the same as the order in the created objects. And if i understand your question then dp1, dp2 should be the expected order.

**Comment by dougsyer** [comment]
Okay thanks should reordering be detected as a template change on install/update?

**Comment by j053ph4** [comment]
Good question -- it should be if we did our homework correctly but I don't remember specifically testing that scenario.  Please advise if it doesn't and I'll open a JIRA for it.

**Comment by dougsyer** [comment]
Tks
